globals:
  seed: 1996
  max_epochs: 300
  n_splits: 5
  use_folds:
    - 0
    - 1
    - 2
    - 3
    - 4
  debug: False
  exp_message: dataset_v1_wifi80_time_diff4000
  notes: time_diffが3s以内のデータのみ使用 -1000は次のwaypointとする
  model_save: True
  pretrained: False
  pretrained_path: None # ../../model/exp005/

loss:
  name: MSELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.0008

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.1
    patience: 3

loader:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 512
    shuffle: False
    num_workers: 4
  test:
    batch_size: 512
    shuffle: False
    num_workers: 4