version: '2.3'

services:
  app:
    build: .
    shm_size: '64gb'
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - $PWD:/work/
    ports:
      - 8888:8888
      - 5000:5000
      - 6006:6006
    tty: true
    stdin_open: True 
    hostname: whale
    # container_name: ubuntu18
    # command: jupyter lab --ip=0.0.0.0 --allow-root --no-browser
