globals:
  seed: 1996
  max_epochs: 300
  n_splits: 5
  use_folds:
    - 0
    - 1
    - 2
    - 3
    - 4
  debug: False
  exp_message: add_waypoint_for_snap
  notes: snap2grid用のtrain waypointに補正分も加える
  only_pred: True
  model_save: False
  pretrained: True
  pretrained_path: ../../model/exp011/

loss:
  name: MSELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.1
    patience: 3

loader:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 512
    shuffle: False
    num_workers: 4
  test:
    batch_size: 512
    shuffle: False
    num_workers: 4