globals:
  seed: 1996
  max_epochs: 10000
  n_splits: 5
  use_folds:
    - 0
#     - 1
#     - 2
#     - 3
#     - 4
  debug: False
  exp_message: local-feature
  notes: local feature for LSTM window 1s
  only_pred: False 
  model_save: True
  pretrained: False
  pretrained_path: # ../../model/exp007/

loss:
  name: MSELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.07

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.1
    patience: 3

loader:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 512
    shuffle: False
    num_workers: 4
  test:
    batch_size: 512
    shuffle: False
    num_workers: 4