globals:
  seed: 1996
  max_epochs: 300
  n_splits: 5
  use_folds:
    - 0
    - 1
    - 2
    - 3
    - 4
  debug: False
  exp_message: pseudo_labeling
  notes: pseudo labeling(モデル保存用) 後処理をいじる
  only_pred: False 
  model_save: True
  pretrained: True
  pretrained_path: ../../model/exp007/

loss:
  name: MSELoss
  params:

optimizer:
  name: Adam
  params:
    lr: 0.001

scheduler:
  name: ReduceLROnPlateau
  params:
    factor: 0.1
    patience: 3

loader:
  train:
    batch_size: 512
    shuffle: True
    num_workers: 4
  valid:
    batch_size: 512
    shuffle: False
    num_workers: 4
  test:
    batch_size: 512
    shuffle: False
    num_workers: 4